<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationIcon>Assets\app_icon.ico</ApplicationIcon>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<AssemblyName>Tyrian Lens</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DiscordRichPresence" Version="1.6.1.70" />
		<PackageReference Include="Gw2Sharp" Version="1.7.4" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3856.49" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

	<ItemGroup>
		<!-- Front-end Modules -->
		<Content Include="modules\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		
		<!-- Static Data / Databases -->
		<Content Include="Data\timers_config.json;Data\manifest.json;Data\nodes_wood.json;Data\nodes_achievements.json;Data\nodes_chests.json;Data\nodes_map_specific.json;Data\nodes_ore.json;Data\nodes_plants.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<None Include="Data\**" Exclude="Data\timers_config.json;Data\manifest.json;Data\nodes_wood.json;Data\nodes_achievements.json;Data\nodes_chests.json;Data\nodes_map_specific.json;Data\nodes_ore.json;Data\nodes_plants.json">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		
		<!-- Assets (Icons, Sounds, Fonts, Leaflet) -->
		<Content Include="Assets\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<None Remove="temp\**;scratch\**" />
		<Compile Remove="temp\**;scratch\**" />
	</ItemGroup>

</Project>